offers:
  mozo0:
    alias: "sorli"
    url: "https://www.infojobs.net/barcelona/preparador-pedidos-mercabarna-lunes-viernes/of-i4a95a578d7482bb7b89d67c64ec26c?applicationOrigin=search-new%7Celement%7E57818912314&searchId=57818912314&page=2&sortBy=RELEVANCE"
  mozo1:
    alias: "piera"
    url: "https://www.infojobs.net/sant-just-desvern/mozo-almacen/of-id005bcd3d34916a68eeb1622c84ff5?applicationOrigin=search-new%7Celement%7E57802344742&searchId=57802344742&page=1&sortBy=RELEVANCE"
  admin0:
    alias: "mutuam"
    url: "https://www.infojobs.net/barcelona/auxiliar-facturacio-amb-treball-2-tardes/of-iec0762065645e6904a9068da0c7b32?applicationOrigin=search-new%7Celement%7E57816424956&searchId=57816424956&page=1&sortBy=RELEVANCE"
  admin1:
    alias: "sants"
    url: "https://www.infojobs.net/barcelona/auxiliar-administrativo/of-i80758a6ba9427db609efe94fa9598c?applicationOrigin=search-new%7Celement%7E57816424956&searchId=57816424956&page=1&sortBy=RELEVANCE"